#!/usr/bin/env bash
#
# pivot.sh
#
# Bring up a SOCKS pivot with chisel or ligolo-ng, write a matching proxychains
# config, and print the command to run on the remote agent. 'down' tears it all
# back down. Keeps its own proxychains config so it never touches /etc.
#
# Usage:
#   ./pivot.sh chisel --port 8080 --socks 1080    # reverse SOCKS via chisel
#   ./pivot.sh ligolo --socks 1080                # ligolo-ng proxy
#   ./pivot.sh proxychains 1080                   # just (re)write the config
#   ./pivot.sh status
#   ./pivot.sh down
#
# Then run tools through it:  proxychains4 -f <state>/proxychains.conf <cmd>
#
set -uo pipefail

STATE_DIR="${PIVOT_STATE:-$HOME/.local/share/parrot-pivot}"
PXY_CONF="$STATE_DIR/proxychains.conf"
PID_FILE="$STATE_DIR/pivot.pid"

PORT=8080
SOCKS=1080

die()  { echo "ERROR: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

usage() {
  grep '^#' "$0" | sed 's/^# \{0,1\}//' | sed '/^!/d'
  exit "${1:-0}"
}

write_proxychains() { # socks-port
  mkdir -p "$STATE_DIR"
  cat > "$PXY_CONF" <<EOF
# generated by pivot.sh
strict_chain
proxy_dns
tcp_read_time_out 15000
tcp_connect_time_out 8000
[ProxyList]
socks5 127.0.0.1 $1
EOF
  echo ">> proxychains config: $PXY_CONF"
  echo ">> use it with: proxychains4 -f $PXY_CONF <command>"
}

record_pid() { echo "$1" > "$PID_FILE"; }

# --- parse args -----------------------------------------------------------
ACTION=""
PXY_ARG=""
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)      usage 0 ;;
    --port)         shift; [ $# -gt 0 ] || die "--port needs a value"; PORT="$1" ;;
    --port=*)       PORT="${1#*=}" ;;
    --socks)        shift; [ $# -gt 0 ] || die "--socks needs a value"; SOCKS="$1" ;;
    --socks=*)      SOCKS="${1#*=}" ;;
    chisel|ligolo|proxychains|status|down)
      [ -z "$ACTION" ] || die "One action at a time."; ACTION="$1" ;;
    *)
      if [ "$ACTION" = "proxychains" ] && [ -z "$PXY_ARG" ]; then PXY_ARG="$1";
      else die "Unexpected argument: $1"; fi ;;
  esac
  shift
done
[ -n "$ACTION" ] || { echo "No action given." >&2; usage 2; }
mkdir -p "$STATE_DIR"

case "$ACTION" in
  # ---------------------------------------------------------------- chisel
  chisel)
    have chisel || die "chisel not found. Install it (apt install chisel, or grab the release binary)."
    echo ">> Starting chisel reverse server on :$PORT (SOCKS will surface on :$SOCKS)..."
    chisel server --reverse --port "$PORT" >"$STATE_DIR/chisel.log" 2>&1 &
    record_pid "$!"
    sleep 1
    write_proxychains "$SOCKS"
    cat <<EOF

>> On the target/agent, run:
     chisel client YOUR_IP:$PORT R:$SOCKS:socks

>> Server log: $STATE_DIR/chisel.log
>> Tear down with: $0 down
EOF
    ;;
  # ---------------------------------------------------------------- ligolo
  ligolo)
    if have ligolo-proxy; then LP=ligolo-proxy
    elif have proxy;      then LP=proxy
    else die "ligolo-ng proxy not found (ligolo-proxy)."; fi
    echo ">> Starting $LP (self-signed) ..."
    echo ">> Note: ligolo needs a tun interface. In another shell:"
    echo "     sudo ip tuntap add user \$USER mode tun ligolo && sudo ip link set ligolo up"
    "$LP" -selfcert >"$STATE_DIR/ligolo.log" 2>&1 &
    record_pid "$!"
    write_proxychains "$SOCKS"
    cat <<EOF

>> On the target/agent, run the matching ligolo agent:
     agent -connect YOUR_IP:11601 -ignore-cert

>> In the ligolo proxy console: session, then 'start' after adding a route to
   the target subnet:  sudo ip route add <subnet> dev ligolo
>> Log: $STATE_DIR/ligolo.log   Tear down: $0 down
EOF
    ;;
  # ----------------------------------------------------------- proxychains
  proxychains)
    [ -n "$PXY_ARG" ] && SOCKS="$PXY_ARG"
    write_proxychains "$SOCKS"
    ;;
  # ---------------------------------------------------------------- status
  status)
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
      echo ">> pivot running (pid $(cat "$PID_FILE"))"
    else
      echo ">> no pivot process tracked as running"
    fi
    [ -f "$PXY_CONF" ] && { echo ">> proxychains config:"; sed 's/^/   /' "$PXY_CONF"; }
    ;;
  # ------------------------------------------------------------------ down
  down)
    if [ -f "$PID_FILE" ]; then
      pid=$(cat "$PID_FILE")
      if kill -0 "$pid" 2>/dev/null; then
        echo ">> stopping pivot process (pid $pid)..."
        kill "$pid" 2>/dev/null || true
      fi
      rm -f "$PID_FILE"
    else
      echo ">> nothing tracked to stop."
    fi
    echo ">> (proxychains config left at $PXY_CONF; remove it by hand if you want)"
    ;;
esac
